apiVersion: v2
name: Pico
description: A Helm chart for Pico
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: nfs-subdir-external-provisioner
  version: 4.0.2
  condition: nfs-subdir-external-provisioner.enabled 
  repository: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner"
- name: ingress-nginx
  version: 4.2.3
  condition: ingress-nginx.enabled
  repository: https://kubernetes.github.io/ingress-nginx
- name: kube-prometheus-stack
  version: 39.9.0
  condition: kube-prometheus-stack.enabled
  repository: https://prometheus-community.github.io/helm-charts
