kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-cm
data:
  nginx.conf: |
    upstream PicoSchool {
        server pico-svc.development.svc.cluster.local:{{ .Values.picoApp.service.targetPort }};
    }
    server {
        listen 80;
        location / {
            proxy_pass http://PicoSchool;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            #proxy_redirect off;
        }
        location /static/ {
            alias /home/app/staticfiles/;
        }
    }
