apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pico-static-files-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.picoApp.pvc.storage }}
