apiVersion: v2
name: postgres
description: Seting up postgres

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
- name: postgres-operator
  version: 1.8.2
  repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
